# ruff.toml

line-length = 88
indent-width = 4

[format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true

[lint]
select = [
    "B",    # flake8-bugbear
    "C",    # flake8-comprehensions
    "D",    # pydocstyle
    "D213", # docstring starts 2nd line
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "W"     # pycodestyle warnings
]

ignore = [
    "D212", # incompatible with D213
    "B008"  # ignore B008 rule
]

task-tags = ["TODO", "todo"]

# In ruff.toml, it is cleaner to use a section for ignores rather than an inline table
[lint.per-file-ignores]
"tests/*" = ["D100", "D103", "D104"]  # test modules/functions don't need docstrings

[lint.pycodestyle]
ignore-overlong-task-comments = true

[lint.mccabe]
max-complexity = 15

[lint.pydocstyle]
convention = "google"