"""
Aggregate answers into empirical and weighted resample-mean distributions.

Missing answers receive probability according to their observed frequency. The
remaining probability is assigned to numeric answers proportional to their
confidence.

The resample-mean distribution is generated by sampling answers with
replacement using confidence as the sampling probability, then calculating the
unweighted mean of the numeric values in each resample.
"""

from __future__ import annotations

from typing import Sequence

import numpy as np
from numpy.typing import NDArray

from semantic_montecarlo.observability import get_logger
from semantic_montecarlo.schemas.models import Distribution
from semantic_montecarlo.schemas.search import NumericAnswer

_logger = get_logger(__name__)

_MAX_FLOAT_ULPS = 4


def bootstrap(
    samples: Sequence[NumericAnswer],
    *,
    n_resamples: int = 10_000,
    seed: int | None = None,
) -> tuple[Distribution, Distribution]:
    """
    Build the empirical distribution and weighted resample-mean distribution.

    Args:
        samples: Numeric answers exposing ``value`` and ``confidence``.
        n_resamples: Number of weighted resamples.
        seed: Optional random seed.

    Returns:
        The empirical distribution followed by the resample-mean distribution.

    Raises:
        ValueError: If ``samples`` is empty or ``n_resamples`` is not positive.
    """
    if not samples:
        raise ValueError("samples must not be empty")
    if n_resamples < 1:
        raise ValueError("n_resamples must be positive")

    values = np.fromiter(
        (np.nan if sample.value is None else sample.value for sample in samples),
        dtype=np.float64,
        count=len(samples),
    )
    confidences = np.fromiter(
        (sample.confidence for sample in samples),
        dtype=np.float64,
        count=len(samples),
    )

    probabilities = _sampling_probabilities(values, confidences)

    empirical = _empirical_distribution(
        values,
        probabilities,
    )
    bootstrap_means = _bootstrap_mean_distribution(
        values,
        probabilities,
        n_resamples=n_resamples,
        seed=seed,
    )

    _logger.debug(
        "bootstrap: %d samples -> %d empirical values, %d distinct resample means",
        len(samples),
        len(empirical.data),
        len(bootstrap_means.data),
    )

    return empirical, bootstrap_means


def _sampling_probabilities(
    values: NDArray[np.float64],
    confidences: NDArray[np.float64],
) -> NDArray[np.float64]:
    """
    Allocate missing-answer mass by frequency and numeric mass by confidence.

    Numeric observations fall back to equal probability when all their
    confidence scores are zero.
    """
    numeric_mask = ~np.isnan(values)
    probabilities = np.full(values.size, 1.0 / values.size)

    numeric_confidences = confidences[numeric_mask]
    total_numeric_confidence = numeric_confidences.sum()

    if total_numeric_confidence > 0.0:
        numeric_probability = numeric_mask.mean()
        probabilities[numeric_mask] = (
            numeric_probability * numeric_confidences / total_numeric_confidence
        )

    return probabilities


def _empirical_distribution(
    values: NDArray[np.float64],
    probabilities: NDArray[np.float64],
) -> Distribution:
    numeric_mask = ~np.isnan(values)

    numeric_values = values[numeric_mask]
    numeric_probabilities = probabilities[numeric_mask]

    no_answer_probability = probabilities[~numeric_mask].sum()
    if not numeric_values.size:
        return Distribution(data=[], no_answer_probability=1.0)

    numeric_probabilities /= numeric_probabilities.sum()

    unique_values, inverse = np.unique(
        numeric_values,
        return_inverse=True,
    )
    aggregated_probabilities = np.bincount(
        inverse,
        weights=numeric_probabilities,
    )

    data = list(
        zip(
            unique_values.tolist(),
            aggregated_probabilities.tolist(),
            strict=True,
        )
    )

    return Distribution(
        data=data,
        no_answer_probability=float(no_answer_probability),
    )


def _bootstrap_mean_distribution(
    values: NDArray[np.float64],
    probabilities: NDArray[np.float64],
    *,
    n_resamples: int,
    seed: int | None,
) -> Distribution:
    rng = np.random.default_rng(seed)

    resampled_indices = rng.choice(
        values.size,
        size=(n_resamples, values.size),
        replace=True,
        p=probabilities,
    )
    resampled_values = values[resampled_indices]

    numeric_counts = np.sum(~np.isnan(resampled_values), axis=1)
    numeric_sums = np.nansum(resampled_values, axis=1)

    answered_mask = numeric_counts > 0
    means = numeric_sums[answered_mask] / numeric_counts[answered_mask]

    data = _aggregate_close_means(means)

    return Distribution(
        data=data,
        no_answer_probability=float(np.mean(~answered_mask)),
    )


def _aggregate_close_means(means: NDArray[np.float64]) -> list[tuple[float, float]]:
    """Combine resample means separated by only a few floating-point steps."""
    if not means.size:
        return []

    sorted_means = np.sort(means)
    left = sorted_means[:-1]
    right = sorted_means[1:]
    tolerance = _MAX_FLOAT_ULPS * np.maximum(
        np.spacing(np.abs(left)),
        np.spacing(np.abs(right)),
    )
    new_group = np.concatenate(
        (
            np.array([True]),
            np.abs(right - left) > tolerance,
        )
    )
    groups = np.cumsum(new_group) - 1
    counts = np.bincount(groups)
    representative_means = sorted_means[new_group]
    probabilities = counts / counts.sum()

    return list(
        zip(
            representative_means.tolist(),
            probabilities.tolist(),
            strict=True,
        )
    )
