"""
Aggregate numeric answers into an empirical distribution and a weighted
resample-mean distribution.

The empirical distribution assigns probability to each numeric answer
proportional to its confidence.

The resample-mean distribution is generated by sampling answers with
replacement using confidence as the sampling probability, then calculating the
unweighted mean of the numeric values in each resample.
"""

from __future__ import annotations

from typing import Sequence

import numpy as np
from numpy.typing import NDArray

from semantic_montecarlo.observability import get_logger
from semantic_montecarlo.schemas.models import Distribution
from semantic_montecarlo.schemas.search import NumericAnswer

_logger = get_logger(__name__)


def bootstrap(
    samples: Sequence[NumericAnswer],
    *,
    n_resamples: int = 10_000,
    seed: int | None = None,
) -> tuple[Distribution, Distribution]:
    """
    Build the empirical distribution and weighted resample-mean distribution.

    Args:
        samples: Numeric answers exposing ``value`` and ``confidence``.
        n_resamples: Number of weighted resamples.
        seed: Optional random seed.

    Returns:
        The empirical distribution and resample-mean distribution.
    """
    values = np.fromiter(
        (
            np.nan if sample.value is None else sample.value
            for sample in samples
        ),
        dtype=np.float64,
        count=len(samples),
    )
    confidence = np.fromiter(
        (sample.confidence for sample in samples),
        dtype=np.float64,
        count=len(samples),
    )

    probabilities = confidence / confidence.sum()

    empirical = _empirical_distribution(
        values,
        probabilities,
    )
    bootstrap_means = _bootstrap_mean_distribution(
        values,
        probabilities,
        n_resamples=n_resamples,
        seed=seed,
    )

    _logger.debug(
        "bootstrap: %d samples -> %d empirical values, "
        "%d distinct resample means",
        len(samples),
        len(empirical.data),
        len(bootstrap_means.data),
    )

    return empirical, bootstrap_means


def _empirical_distribution(
    values: NDArray[np.float64],
    probabilities: NDArray[np.float64],
) -> Distribution:
    numeric_mask = ~np.isnan(values)

    numeric_values = values[numeric_mask]
    numeric_probabilities = probabilities[numeric_mask]

    no_answer_probability = probabilities[~numeric_mask].sum()
    numeric_probabilities /= numeric_probabilities.sum()

    unique_values, inverse = np.unique(
        numeric_values,
        return_inverse=True,
    )
    aggregated_probabilities = np.bincount(
        inverse,
        weights=numeric_probabilities,
    )

    data = list(
        zip(
            unique_values.tolist(),
            aggregated_probabilities.tolist(),
            strict=True,
        )
    )

    return Distribution(
        data=data,
        no_answer_probability=float(no_answer_probability),
    )


def _bootstrap_mean_distribution(
    values: NDArray[np.float64],
    probabilities: NDArray[np.float64],
    *,
    n_resamples: int,
    seed: int | None,
) -> Distribution:
    rng = np.random.default_rng(seed)

    resampled_indices = rng.choice(
        values.size,
        size=(n_resamples, values.size),
        replace=True,
        p=probabilities,
    )
    resampled_values = values[resampled_indices]

    numeric_counts = np.sum(~np.isnan(resampled_values), axis=1)
    numeric_sums = np.nansum(resampled_values, axis=1)

    answered_mask = numeric_counts > 0
    means = numeric_sums[answered_mask] / numeric_counts[answered_mask]

    unique_means, counts = np.unique(
        means,
        return_counts=True,
    )
    mean_probabilities = counts / counts.sum()

    data = list(
        zip(
            unique_means.tolist(),
            mean_probabilities.tolist(),
            strict=True,
        )
    )

    return Distribution(
        data=data,
        no_answer_probability=float(np.mean(~answered_mask)),
    )
